version: '3'
services:
  go:
    container_name: "go-container"
    build: ./build/
    volumes:
      - ./cmd:/go/src/cmd
    env_file:
      - ./build/.go_env
      - ./build/.secret_env
    tty: true
    
