version: '3'
services:
  go:
    container_name: "go-container"
    build: ./build/
    volumes:
      - ./cmd:/go/src/cmd
    env_file:
      - ./build/.go_env
<<<<<<< Updated upstream
      - ./build/.secret_keys
=======
      - ./build/.secret_env
>>>>>>> Stashed changes
    tty: true
    